
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: '*/docker-compose.yml'
    dockerComposeFileArgs: |
      COMPOSE_DOCKER_CLI_BUILD=1
            DOCKER_BUILDKIT=1
    action: 'Run services'
    detached: false




