
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: 'COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1'