
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(89332acc-e99a-4a6e-8d22-d9115e1c77d1)'
    appType: 'webAppContainer'
    WebAppName: 'lakesidedocker'
    deployToSlotOrASE: true
    ResourceGroupName: 'docker-rg'
    SlotName: 'production'
    DockerNamespace: 'lakesidedockerregistry.azurecr.io'
    DockerRepository: 'severindellspergerlakesidemutual_app'
