trigger:
- master

resources:
- repo: self

  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'build'
    Dockerfile: 'customer-core/Dockerfile'
    arguments: |
      COMPOSE_DOCKER_CLI_BUILD=1
      DOCKER_BUILDKIT=1

- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'push'
    Dockerfile: 'customer-core/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'build'
    Dockerfile: 'customer-management-backend/Dockerfile'
    arguments: |
      COMPOSE_DOCKER_CLI_BUILD=1
      DOCKER_BUILDKIT=1

- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'push'
    Dockerfile: 'customer-management-backend/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'build'
    Dockerfile: 'customer-management-frontend/Dockerfile'
    arguments: |
      COMPOSE_DOCKER_CLI_BUILD=1
      DOCKER_BUILDKIT=1

- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'push'
    Dockerfile: 'customer-management-frontend/Dockerfile'
