# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-javascript-docker'
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1


steps:
- task: Docker@2
  displayName: Build customer-core
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    repository: customer-core
    command: build
    Dockerfile: customer-core/Dockerfile

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    repository: customer-management-backend
    command: buildAndPush
    Dockerfile: customer-management-backend/Dockerfile

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    repository: customer-management-frontend
    command: buildAndPush
    Dockerfile: customer-management-frontend/Dockerfile