trigger:
- master

resources:
- repo: self

  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'buildAndPush'
    Dockerfile: 'customer-core/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'buildAndPush'
    Dockerfile: 'customer-management-backend/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'LakeSideDockerRegistry'
    command: 'buildAndPush'
    Dockerfile: 'customer-management-frontend/Dockerfile'

